//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bank_Account
    {
        public int Bank_Id { get; set; }
        public string Account_Holder_Name { get; set; }
        public string Bank_Account_No { get; set; }
        public string BSB_No { get; set; }
        public string Account_No { get; set; }
        public string Bank_Name { get; set; }
        public string Bank_Type { get; set; }
        public int Balace { get; set; }
        public string Remark { get; set; }
    }
}
