//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class distribution
    {
        public int Distribution_Id { get; set; }
        public int Fund_Id { get; set; }
        public int amount { get; set; }
        public System.DateTime date_time { get; set; }
        public int distribute_by { get; set; }
        public string distribute_purpose { get; set; }
        public int candidate_Id { get; set; }
    }
}
