//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fund_distribution
    {
        public int Fund_Distribution_Id { get; set; }
        public int Fund_Id { get; set; }
        public int amount { get; set; }
        public int candidate_application_id { get; set; }
        public string money_transfer_method { get; set; }
        public int distribute_by { get; set; }
        public System.DateTime distribution_date { get; set; }
    
        public virtual Fund Fund { get; set; }
        public virtual Member Member { get; set; }
        public virtual Member Member1 { get; set; }
        public virtual ScholarshipCandidateTable ScholarshipCandidateTable { get; set; }
    }
}
