//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fund_Contribution
    {
        public int Fund_Contribution_Id { get; set; }
        public Nullable<int> Fund_Id { get; set; }
        public Nullable<int> Contributor_Id { get; set; }
        public Nullable<int> amount { get; set; }
        public Nullable<System.DateTime> dateandtime { get; set; }
        public string bank_account_Id { get; set; }
        public string Proof_of_Contribution { get; set; }
    
        public virtual Fund Fund { get; set; }
        public virtual Member Member { get; set; }
    }
}
