//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScholarshipCandidateTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ScholarshipCandidateTable()
        {
            this.Fund_distribution = new HashSet<Fund_distribution>();
        }
    
        public int CandidateId { get; set; }
        public string CandidateName { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string Address { get; set; }
        public string picture { get; set; }
        public int AnjumanStudentID { get; set; }
        public string FinalExamResultClass8 { get; set; }
        public string FinancialConditionOfFamily { get; set; }
        public string SourceOfFamilyIncome { get; set; }
        public int MonthlyFamilyIncome { get; set; }
        public int NumberOfDependence { get; set; }
        public string ContactPhoneNumber { get; set; }
        public string ContactEmailAddress { get; set; }
        public string DescribeAboutYourself { get; set; }
        public string ConnectedWithOtherAlumni { get; set; }
        public string NameOfAlumni { get; set; }
        public string TeacherReference1 { get; set; }
        public string TeacherPhoneNumRef1 { get; set; }
        public string TeacherReference2 { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string TeacherPhoneNumRef2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fund_distribution> Fund_distribution { get; set; }
    }
}
