//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecurityCodeCD
    {
        public int SecurityCodeId { get; set; }
        public string SecurityCodeDesc { get; set; }
        public byte[] VerificationFlag { get; set; }
    }
}
